version: "3"
services:
  backend:
    build: .
    image: imsamad/teapost_server:1.0.0
    container_name: teapost_backend
    env_file:
      - ./config/.env
    command: npm start

  nginx:
    build: ./nginx
    image: imsamad/teapost_nginx:1.0.0
    container_name: teapost_nginx
    ports:
      - "80:80"
    depends_on:
      - backend

  watchtower:
    depends_on:
      - nginx
      - backend
    image: containrrr/watchtower
    container_name: watch_tower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_TRACE=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_POLL_INTERVAL=50
    command: teapost_backend teapost_nginx

volumes:
  mongoVal:
