version: "3"
services:
  backend:
    build: .
    # deploy:
    #   replicas: 4
    #   restart_policy:
    #     condition: any

    #   update_config:
    #     parallelism: 2
    #     delay: 10s

    image: imsamad/teapost_server:1.0.1
    # container_name: teapost_backend
    env_file:
      - ./config/.env
    command: npm start

  nginx:
    build: ./nginx
    image: imsamad/teapost_nginx:1.0.0
    # container_name: teapost_nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongoVal:
